import 'bootstrap/dist/css/bootstrap.css'
import './assets/vendor/animate/animate.compat.css'
import './assets/vendor/fontawesome-free/css/all.min.css'
import './assets/vendor/simple-line-icons/css/simple-line-icons.min.css'
import './assets/vendor/owl.carousel/owl.carousel.min.css'
import './assets/vendor/owl.carousel/owl.theme.default.min.css'

import './assets/css/theme-elements.css'
import './assets/css/theme.css'

import './assets/css/demos/demo-auto-services.css'
import './assets/css/skins/skin-auto-services.css'

import Foot from './components/template/footer/Foot'
import Header from './components/template/header/Header'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='body'>
          <Header/>
          {children}
          <Foot/>
        </div>
      </body>
    </html>
  )
}
